# 888    d8P  8888888888 8888888b.  888b     d888 8888888 888b    888        d8888 888
# 888   d8P   888        888   Y88b 8888b   d8888   888   8888b   888       d88888 888
# 888  d8P    888        888    888 88888b.d88888   888   88888b  888      d88P888 888
# 888d88K     8888888    888   d88P 888Y88888P888   888   888Y88b 888     d88P 888 888
# 8888888b    888        8888888P"  888 Y888P 888   888   888 Y88b888    d88P  888 888
# 888  Y88b   888        888 T88b   888  Y8P  888   888   888  Y88888   d88P   888 888
# 888   Y88b  888        888  T88b  888   "   888   888   888   Y8888  d8888888888 888
# 888    Y88b 8888888888 888   T88b 888       888 8888888 888    Y888 d88P     888 88888888
#

ConnectionType: 'mysql'
Connection:
  Host: 'localhost'
  Database: 'kerminal'
  Port: 3306
  Username: 'root'
  Password: ''


########################################
#                 Homes                #
########################################
HomeSystem:
  # Mundos proibidos de definir uma home
  BlacklistWorlds:
    - "worldName"


########################################
#                 Motd                 #
########################################
Motd:
  MaxPlayers: 10
  Normal:
    - "&aFirst motd"
    - "&bSecond motd"
    - "&cThird motd"
  Maintenance:
    - "&aThis server in Maintenance"
    - "&bThis server in Maintenance"
    - "&cThis server in Maintenance"

########################################
#             Teleportes               #
########################################
Teleport:
  # Defina o tempo de teleportar (EM SEGUNDOS)
  Delay: 3


########################################
#             Regeneração              #
########################################
Regeneration:
  # Ative ou desative o sistema
  Enabled: false
  # Defina o tempo da regeneração da vida (EM TICKS)
  Delay: 20


########################################
#         Comandos Bloqueados          #
########################################
BlockedCommands:
  - "plugins"
  - "pl"

########################################
#       Mundos bloqueados de voar      #
########################################
BlockWorldsFly:
  - "exampleWorld"

########################################
#        Recursos do Kerminal          #
########################################
Features:
  # Permite trocar as mensagens de Entrada, Saida e Morte
  CustomMessages:
    Enabled: true
    # Para não exibir nenhuma mensagem, deixe vazio.
    # Placeholders: %player% (Nome do jogador)
    PlayerJoin: ""
    # Para não exibir nenhuma mensagem, deixe vazio.
    # Placeholders: %player% (Nome do jogador)
    PlayerQuit: ""
    # Configuração da mensagem de morte
    PlayerDeath:
      # Modos:
      # ALL - Exibe a mensagem default para todos online
      # PRIVATE - Exibe as mensagens privadas apenas para assassino e vitima
      Mode: ALL
      # Para não exibir nenhuma mensagem, deixe vazio.
      DefaultMessage: ""
      PrivateAnnounces:
        Killer: "&aVocê acabou de matar %player%."
        Victim: "&aVocê foi morto por %player%."
  # Envia mensagens aos jogadores de tempo em tempo
  AutoMessage:
    Enabled: true
    # Intervalo de tempo entre as mensagens
    # O valor está em segundos
    Delay: 240
    # Som que será enviado para todos a cada mensagem
    # Para não realizar nenhum som, defina como: "false"
    Sound: CAT_MEOW
    # Lista de mensagens automáticas em ordem
    Messages:
      - "&a【Anúncio】 &fObrigado por usar o Kerminal :3"
      - "&a【Anúncio】 &fO que acha de mandar o Kerminal para seus amigos?"
      - "&a【Anúncio】 &fSe precisar falar com os desenvolvedores, entre na BeezCommunity."
      - "&a【Anúncio】 &fQuer adicionar algo no Kerminal? Envia sua sugestão para nós ;)"
  # Algumas opções para customizar os mundos
  WorldOptions:
    # Bloqueia a queda das folhas das arvores
    Block-Decay-Leaves: true
    # Bloqueia o jogador de cair no void (Teleporta pro spawn)
    Block-Void-Damage: true
    # Bloqueia de ocorrer chuvas
    Block-Weather: true
    # Bloqueia de derreter o gelo
    Block-Smelt-Snow: true
    # Bloqueia de criar portais
    Block-Create-Portal: true
    # Bloqueia os jogadores de ficarem com fome
    # Na lista abaixo você define os mundos que ficarão sem fome
    Block-Food-Down: true
    FoodWorlds:
      - "world"
    # Bloqueia itens de explodirem
    Block-Explode-Item: true
    # Bloqueia plantações de quebrarem pulando
    Block-Plantation-Destroy: true
    # Bloqueia de congelar a água
    Block-Freeze-Water: true
    # Bloqueia as entidades de pegarem fogo
    Block-Entity-Burn: true
    # Bloqueia as entidades de roubarem itens
    Block-Entity-Steal-Item: true
    # Bloqueia o fogo de se espalhar pelo mapa
    Block-Fire-Spred: true

########################################
#        Opções do Comando Back        #
########################################
BackSystem:
  # Lista de mundos onde não é possível voltar com /back
  BlacklistWorlds:
    - "worldName"


########################################
#      Opções dos Mundos em Ticks      #
########################################
Worlds:
  # Defina o nome do mundo
  world:
    # A quantidade da aceleração dos ticks do mundo
    # Isso afetará o crescimento de plantações, grama, etc...
    Tick: 60