# 888    d8P  8888888888 8888888b.  888b     d888 8888888 888b    888        d8888 888
# 888   d8P   888        888   Y88b 8888b   d8888   888   8888b   888       d88888 888
# 888  d8P    888        888    888 88888b.d88888   888   88888b  888      d88P888 888
# 888d88K     8888888    888   d88P 888Y88888P888   888   888Y88b 888     d88P 888 888
# 8888888b    888        8888888P"  888 Y888P 888   888   888 Y88b888    d88P  888 888
# 888  Y88b   888        888 T88b   888  Y8P  888   888   888  Y88888   d88P   888 888
# 888   Y88b  888        888  T88b  888   "   888   888   888   Y8888  d8888888888 888
# 888    Y88b 8888888888 888   T88b 888       888 8888888 888    Y888 d88P     888 88888888
#

ConnectionType: 'mysql'
Connection:
  Host: 'localhost'
  Database: 'kerminal'
  Port: 3306
  Username: 'root'
  Password: ''

HomeSystem:
  MaxHomes: 3
  BlacklistWorlds:
    - "worldName"

Motd:
  MaxPlayers: 10
  Normal:
    - "&aFirst motd"
    - "&bSecond motd"
    - "&cThird motd"
  Maintenance:
    - "&aThis server in Maintenance"
    - "&bThis server in Maintenance"
    - "&cThis server in Maintenance"

Regeneration:
  Enabled: false
  Delay: 20

BlockedCommands:
  - "plugins"
  - "pl"

Features:
  CustomMessages:
    Enabled: true
    PlayerJoin: ""
    PlayerQuit: ""
    PlayerDeath:
      Mode: ALL
      DefaultMessage: ""
      PrivateAnnounces:
        Killer: "&aVocê acabou de matar %player%."
        Victim: "&aVocê foi morto por %player%."
  AutoMessage:
    Enabled: true
    Delay: 30
    Sound: CAT_MEOW
    Messages:
      - "&a【Anúncio】 &fObrigado por usar o Kerminal :3"
      - "&a【Anúncio】 &fO que acha de mandar o Kerminal para seus amigos?"
      - "&a【Anúncio】 &fSe precisar falar com os desenvolvedores, entre na BeezCommunity."
      - "&a【Anúncio】 &fQuer adicionar algo no Kerminal? Envia sua sugestão para nós ;)"

BackSystem:
  BlacklistWorlds:
    - "worldName"

Worlds:
  world:
    Tick: 60

Spawn: {}