test:
  Sound: NOTE_PLING
  Delay: 5
  MessageDelay: "&cAguarde %time% para usar test novamente."
  Message:
    - "&eA test"
test2:
  Sound: NOTE_PLING
  Location:
    world: mundo
    x: 100
    y: 255
    z: 100
  Message:
    - "&eThis is a test"